### PR TITLE
Replace local player type definitions with types from player v8

### LINKED ISSUE #106: [TS] Incorrect DRMConfig type
Right now we have empty `DRMConfig` interface:
```ts
interface DRMConfig {
}
```
which is extended by other types, like:
```ts
interface WidevineModularDRMConfig extends DRMConfig {
  //...
}
```
I would propose renaming it to `BaseDRMConfig` if there are some common fields.
Then the `DRMConfig` would be:
```ts
interface DRMConfig = {
  playready: PlayReadyDRMConfig;
  widevine: WidevineModularDRMConfig;
  // ...
}
```
Which is correct type of `SourceConfig` `drm` property, according to docs:
https://bitmovin-a.akamaihd.net/bitmovin-player/stable/7/docs/interfaces/playerconfigapi.sourceconfig.html

### PR DESCRIPTION
**Pull request by protyposis**
Implements #155 and fixes #106.

### CODE REVIEW

File: src/ts/components/playbacktogglebutton.ts [hunk 1]
```diff
@@ -68,7 +67,7 @@ export class PlaybackToggleButton extends ToggleButton<ToggleButtonConfig> {
 
     // When a playback attempt is rejected with warning 5008, we switch the button state back to off
     // This is required for blocked autoplay, because there is no Paused event in such case
-    player.on(player.exports.Event.Warning, (event: WarningEvent) => {
+    player.on(player.exports.Event.Warning, (event: Events.WarningEvent) => {
       if (event.code === 5008) {
```
Comment (stonko1994) [inline src/ts/components/playbacktogglebutton.ts]: Just to notice. We should update to the new warning codes in a separate PR.

File: src/ts/components/hugeplaybacktogglebutton.ts [hunk 2]
```diff
@@ -98,32 +97,32 @@ export class HugePlaybackToggleButton extends PlaybackToggleButton {
...
 
-    player.on(player.exports.Event.Play, () => {
+    player.on(player.exports.PlayerEvent.Play, () => {
       // Playback has really started, we can disable the flag to switch to normal toggle button handling
       firstPlay = false;
     });
 
-    player.on(player.exports.Event.Warning, (event: WarningEvent) => {
+    player.on(player.exports.PlayerEvent.Warning, (event: WarningEvent) => {
       // 5008 == Playback could not be started
```
Comment (stonko1994) [inline src/ts/components/hugeplaybacktogglebutton.ts]: remove this comment.

File: src/ts/components/vrtogglebutton.ts [hunk 3]
```diff
@@ -34,8 +33,9 @@ export class VRToggleButton extends ToggleButton<ToggleButtonConfig> {
       return player.vr && Boolean(source.vr);
     };
 
-    let vrStateHandler = (ev: PlayerEvent) => {
-      if (ev.type === player.exports.Event.Warning && (ev as WarningEvent).code !== 5006) {
+    let vrStateHandler = (ev: PlayerEventBase) => {
+      if (ev.type === player.exports.PlayerEvent.Warning
+        && (ev as WarningEvent).code !== player.exports.WarningCode.VR_RENDERING_ERROR) {
         // a code of 5006 signals a VR Error, so don't do anything on other warnings
```
Comment (stonko1994) [inline src/ts/components/vrtogglebutton.ts]: remove this comment.
